// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cadozyaqilfayoptemzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhZG96eWFxaWxmYXlvcHRlbXpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MTcwMDUsImV4cCI6MjA2NzI5MzAwNX0.hZ4jdLze7SUd2Rv4_omsGjei2SXYmd6cCUf4yC_miQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});